HW2 is completed
Tiksy1/otus_hw-test pull request #2
Opened 2022-05-15 22:24 UTC by Tiksy1

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-05-16 15:19 UTC, alexus1024 requested changes

2022-05-16 15:19 UTC, alexus1024 commented on hw02_unpack_string/unpack_test.go
> +		{input: "ab 4cd", expected: "ab    cd"},
добавьте кейс с `input:"a"`
кажется, в коде есть проблема в случае если длина входа = 1

2022-05-16 15:19 UTC, alexus1024 commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(b)-1; i++ {
вы делаете два прохода. тут это не страшно, но такой подход лишает вас возможности в будущем адаптировать алгоритм к потоковой обработке. вам всегда надо иметь всю строку в памяти до начала работы.

Для этого задания это значения не имеет, просто для информации.

2022-05-16 15:19 UTC, alexus1024 commented on hw02_unpack_string/unpack.go
> +			tmpAnsw := str.String()
вычитать билдер в строку, почистить его и потом записать туда модифицированное значение. Это довольно неэффективное решение. 
Попробуйте пожалуйста реализовать всё так, чтобы билдер был вашим выходным потоком, вы в него только писали символы и в конце один раз преобразовывали в строку для показа результата

2022-05-16 19:42 UTC, Tiksy1 commented on hw02_unpack_string/unpack_test.go
> +		{input: "ab 4cd", expected: "ab    cd"},
@alexus1024 , добавил, работает, но намек на будущее я понял.

2022-05-17 04:37 UTC, alexus1024 requested changes

2022-05-17 04:37 UTC, alexus1024 commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(b)-1; i++ {
смотрите, у вас тут 2 цикла - один всё проверяет в 22 строке и потом уже - обработка в 27й. Это я и назвал двумя проходами (в смысле, по входным данным)
То есть к моменту второго прохода - вы уже должны проверить всю строку первым циклом, до конца.

Обычно, подобные алгоритмы относительно легко доработать чтобы они могли обрабатывать данные неограниченной длины - сидеть на входном потоке, обрабатывать из него символ за символом и писать в выходной поток. Но у вас вот конкретно с таким подходом этого не выйдет - первый цикл должен обработать все данные до конца, чтобы запустить второй цикл. На это я и обращаю внимание.
Это довольно абстрактные рассуждения и никаких действий в этой работе по этому поводу не требуется.

2022-05-17 04:37 UTC, alexus1024 commented on hw02_unpack_string/unpack_test.go
> +		{input: "ab 4cd", expected: "ab    cd"},
что то не вижу этого теста в коде. Забыли запушить?

2022-05-17 04:37 UTC, alexus1024 commented on hw02_unpack_string/unpack.go
> +			tmpAnsw := str.String()
вот тут не вижу обновлений никаких пока

2022-05-17 05:40 UTC, Tiksy1 commented on hw02_unpack_string/unpack_test.go
> +		{input: "ab 4cd", expected: "ab    cd"},
еще не пушил, проверил локально. Ждал ответов на вопросы.

2022-05-17 05:47 UTC, Tiksy1 commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < len(b)-1; i++ {
да, я понял, что это связано с горутинами. В данном случае у меня возникла проблема out of range потому что я проверяю текущий элемент и следующий на наличие 2-х цифр подряд. Комментарий понятен, если придумаю как решить, исправлю, т.к. самому интересно.

2022-05-17 19:07 UTC, closed without merging